#!/bin/sh

if [ ! -f /etc/opkg.conf ] ; then
	mv /etc/opkg.gpkg.tmp /etc/opkg.conf
else
	rm /etc/opkg.gpkg.tmp
	local plugin_root="/plugin_root"
	local escaped_plugin_root=$(echo "$plugin_root" | sed 's/\//\\\//g' )
	local have_plugin_root=$(cat /etc/opkg.conf | grep "dest.*$escaped_plugin_root" )
	if [ -z "$have_plugin_root" ] ; then
		echo "dest plugin_root $plugin_root" >>/etc/opkg.conf
	fi
fi

if [ ! -e /bin/opkg ] ; then
	ln -s /usr/bin/gpkg /bin/opkg
fi

