#!/bin/sh

# Set hostname to Gargoyle
uci set system.@system[0].hostname="Gargoyle" 2>/dev/null
uci commit                                    2>/dev/null
echo "Gargoyle" > /proc/sys/kernel/hostname   2>/dev/null


# remove init scripts of things that should not be active by default
/etc/init.d/miniupnpd disable       2>/dev/null
/etc/init.d/qos_gargoyle disable    2>/dev/null
/etc/init.d/webmon_gargoyle disable 2>/dev/null

# ensure ntpclient is active
chmod 755 /etc/hotplug.d/iface/20-ntpclient 2>/dev/null

#make sure date isn't set to 1970, which may cause issues with timezones that cause time to go back before unix epoch,  set to Jan 1st 2001
curdate=$(date -u +%s)
if [ $curdate -lt 978307200 ] ; then
	date -u -s 2001.01.01-00:00:01
	mkdir /data
	echo "2001.01.01-00:00:01" >/data/time_backup
fi


#create original backup
sh /usr/lib/gargoyle/create_backup.sh
mkdir /etc/original_backup
cp /tmp/backup/backup.tar.gz /etc/original_backup/backup.tar.gz


