#!/bin/sh

uci set gargoyle.display.system_spect_analyser='Spectrum Analyser'
uci set gargoyle.scripts.system_spect_analyser='spectrum_analyser.sh'
uci set gargoyle.system.spect_analyser='355'
uci commit
