#!/bin/sh /etc/rc.common

START=99
STOP=01
USE_PROCD=1

start_service()
{
	procd_open_instance
	procd_set_param command /bin/sh "/usr/lib/gargoyle/gargoyle_stamgr.sh"
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

stop_service()
{
	[ -e "/tmp/gargoyle_stamgr.json" ] && rm -f /tmp/gargoyle_stamgr.json
}
