#!/bin/sh

menu_name="WiFi Schedule"
[ -n `which i18n` ] && {
	trans=$(i18n-menu gargoyle.display.system_wifi_schedule)
	[ -n "$trans" ] && menu_name="$trans"
	menu_name=${trans:-"$menu_name"}
}
uci set gargoyle.display.system_wifi_schedule="$menu_name"
uci set gargoyle.scripts.system_wifi_schedule='wifi_schedule.sh'
uci set gargoyle.system.wifi_schedule='370'
uci commit
