#!/bin/sh

#82 = Linux swap
#83 = Linux

disk=$1
percent_swap=$2
ext_version=$3

if [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ]  ; then
	echo "Usage: $0 [disk] [percent_swap] [ext_version]"
	exit
fi


touch /tmp/usb_restart.lock


num_partitions=$(fdisk -l $disk | grep "^$disk" | wc -l)
num_p=$num_partitions
while [ "$num_p" -gt 0 ] ; do
	swapoff "$disk$num_p" >/dev/null 2>&1
	umount  "$disk$num_p" >/dev/null 2>&1
	num_p=$(( $num_p - 1 ))
done
while [ "$num_partitions" -gt 0 ] ; do
	if [ "$num_partitions" = "1" ] ; then
		printf "d\nw\n" | fdisk "$disk" >/dev/null 2>&1
	else
		printf "d\n1\nw\n" | fdisk "$disk" >/dev/null 2>&1
	fi
	num_partitions=$(( $num_partitions - 1 ))
done

if [ "$percent_swap" = "100" ] ; then
	printf "n\np\n1\n\n\nt\n82\nw\n" | fdisk "$disk" >/dev/null 2>&1
	sleep 10
	swapoff "$disk"1 >/dev/null 2>&1
	mkswap "$disk"1
elif [ "$percent_swap" = "0" ] ; then
	printf "n\np\n1\n\n\nt\n83\nw\n" | fdisk "$disk" >/dev/null 2>&1
	sleep 10
	mkfs.ext$ext_version "$disk"1
else
	cylinders=$(fdisk -l /dev/sda | awk ' $0 ~ /cylinders$/ { print $5 } ' )
	ext_cylinders=$((  (100-$percent_swap)*$cylinders/100 ))
	if [ "$ext_cylinders" = "0" ] ; then
		ext_cylinders=1
	fi
	if [ "$ext_cylinders" = "$cylinders" ] ; then
		ext_cylinders=$(( $cylinders - 1))
	fi
	echo "ext_cylinders=$ext_cylinders"
	printf "n\np\n1\n\n$ext_cylinders\nt\n83\nn\np\n2\n\n\nt\n2\n82\nw\n" | fdisk "$disk" 
	sleep 10

	
	umount  "$disk"1 >/dev/null 2>&1
	echo mkfs.ext$ext_version "$disk"1
	mkfs.ext$ext_version "$disk"1

	swapoff "$disk"2 >/dev/null 2>&1
	mkswap "$disk"2
fi

rm /tmp/usb_restart.lock
