#!/bin/sh

config_load "network"
config_get wan_proto "wan" "proto"

#only start if we're bringing up wan and ppp isn't being used
#if ppp, it's better to use the /etc/ppp/ip-up.d because ip
#changes will trigger this directory to be run while only
#an interface going up or down will trigger this
if [ "$INTERFACE" = "wan" ] && [ "$ACTION" = "ifup" ] && [ "$wan_proto" != 'pppoe' ]
then
	/usr/bin/ddns_gargoyle -P /etc/ddns_providers.conf -C /etc/ddns_gargoyle.conf
fi


