#!/bin/sh

if [ "$ACTION" = "add" ] || [ "$ACTION" = "remove" ] ; then
	
	
	timeout=15
	while [ -e /tmp/usb_restart.lock ] && [ $timeout -gt 0 ] ; do
		sleep 1
		timeout=$(($timeout - 1))
	done
	if [ ! -e /tmp/usb_restart.lock ] ; then
		touch /tmp/usb_restart.lock	
		
		if [ "$ACTION" = "add" ] ; then sleep 3; fi
		
		/etc/init.d/usb_storage restart
		rm -rf /tmp/usb_restart.lock
	fi
fi
