#undef HAVE_CREAT64
#define HAVE_CREAT64 1

#undef HAVE_FSEEKO64
#define HAVE_FSEEKO64 1

#undef HAVE_FSTAT64
#define HAVE_FSTAT64 1

#undef HAVE_FTELLO64
#define HAVE_FTELLO64 1

#undef HAVE_FTRUNCATE64
#define HAVE_FTRUNCATE64 1

#undef HAVE_LSEEK64
#define HAVE_LSEEK64 1

#undef HAVE_LSTAT64
#define HAVE_LSTAT64 1

#undef HAVE_OPEN64
#define HAVE_OPEN64 1

#undef HAVE_PREAD64
#define HAVE_PREAD64 1

#undef HAVE_PWRITE64
#define HAVE_PWRITE64 1

#undef HAVE_READDIR64
#define HAVE_READDIR64 1

#undef HAVE_STAT64
#define HAVE_STAT64 1

#undef HAVE_STRUCT_FLOCK64
#define HAVE_STRUCT_FLOCK64 1

#undef SIZEOF_LONG_LONG
#define SIZEOF_LONG_LONG 8

#undef SIZEOF_OFF_T
#define SIZEOF_OFF_T 8

#undef _FILE_OFFSET_BITS
#define _FILE_OFFSET_BITS 64

#undef _GNU_SOURCE
#define _GNU_SOURCE 1

#undef _LARGEFILE_SOURCE
#define _LARGEFILE_SOURCE 1

#undef _LARGEFILE64_SOURCE
#define _LARGEFILE64_SOURCE 1
