#!/bin/sh

menu_name="DLNA"
[ -n `which i18n` ] && {
	menu_name=$(i18n-menu gargoyle.display.system_minidlna)
}
uci set gargoyle.display.system_minidlna="$menu_name"
uci set gargoyle.scripts.system_minidlna='minidlna.sh'
uci set gargoyle.system.minidlna='352'
uci commit gargoyle
