#!/bin/sh

menu_name="Ping Watchdog"
[ -n `which i18n` ] && {
	menu_name=$(i18n-menu gargoyle.display.connection_ping_watchdog)
}
uci set gargoyle.display.connection_ping_watchdog="$menu_name"
uci set gargoyle.scripts.connection_ping_watchdog='ping_watchdog.sh'
uci set gargoyle.connection.ping_watchdog='600'
uci commit
