#ifndef _WEBMON_H
#define _WEBMON_H

#define WEBMON_DOMAIN             16
#define WEBMON_SEARCH             32
#define WEBMON_SET              3064
enum nft_timerange_attributes {
	NFTA_WEBMON_UNSPEC,
	NFTA_WEBMON_FLAGS,
	NFTA_WEBMON_MAXDOMAINS,
	NFTA_WEBMON_MAXSEARCHES,
	NFTA_WEBMON_IPS,
	NFTA_WEBMON_DOMAINLOADFILE,
	NFTA_WEBMON_SEARCHLOADFILE,
	NFTA_WEBMON_DOMAINLOADDATA,
	NFTA_WEBMON_DOMAINLOADDATALEN,
	NFTA_WEBMON_SEARCHLOADDATA,
	NFTA_WEBMON_SEARCHLOADDATALEN,
	__NFTA_WEBMON_MAX,
};

#define NFTA_WEBMON_MAX (__NFTA_WEBMON_MAX - 1)

#define WEBMON_TEXT_SIZE 1024

#endif /* _WEBMON_H */