#!/bin/sh

uci set gargoyle.display.connection_openvpn="OpenVPN"
uci set gargoyle.scripts.connection_openvpn="openvpn.sh"
uci set gargoyle.connection.openvpn="225"

uci set gargoyle.scripts.status_openvpn_connections="openvpn_connections.sh"
uci set gargoyle.display.status_openvpn_connections="OpenVPN Status"

uci set openvpn.custom_config.script_security="3"
uci set openvpn.custom_config.up="/etc/openvpn.up"
uci set openvpn.custom_config.down="/etc/openvpn.down"

uci set firewall.openvpn_include_file=include
uci set firewall.openvpn_include_file.path='/etc/openvpn.firewall'

uci commit
