#!/bin/sh

menu_name="Services"
[ -n `which i18n` ] && {
	menu_name=$(i18n-menu gargoyle.display.system_initd)
}
uci set gargoyle.display.system_initd="$menu_name"
uci set gargoyle.scripts.system_initd='initd.sh'
uci set gargoyle.system.initd='310'
uci commit
