#!/bin/sh /etc/rc.common
# Copyright (C) 2008 OpenWrt.org

START=80 

config_cb() {
	local cfg="$CONFIG_SECTION"
	local cfgtype
	config_get cfgtype "$cfg" TYPE

	if [ "$cfgtype" = ntpclient ]
	then
		config_get hostname	$cfg hostname
		config_get port		$cfg port
		config_get count	$cfg count

		ps | grep -q 'bin/[n]tpclient' || \
			/usr/sbin/ntpclient -s -c ${count:-1} -l -h $hostname -p ${port:-123} 2>&- >&- &
	fi
}

start() {
	config_load ntpclient&
}

stop() {
	killall ntpclient 2>&- >&-
}
