#!/bin/sh

menu_name='Webshell'
[ -n `which i18n` ] && {
	menu_name=$(i18n-menu gargoyle.display.system_webshell)
}
uci set gargoyle.display.system_webshell="$menu_name"
uci set gargoyle.scripts.system_webshell='webshell.sh'
uci set gargoyle.system.webshell='312'
uci commit
