#!/bin/sh /etc/rc.common
START=41


start() {
	/etc/init.d/create_original_backup disable
	sh /usr/lib/gargoyle/create_backup.sh
	mkdir /etc/original_backup
	cp /tmp/backup/backup.tar.gz /etc/original_backup/backup.tar.gz
}


