#!/bin/sh /etc/rc.common

START=25

boot()
{
	#set backup date if it exists
	#this makes sure we're in the same ballpark
	#as the correct time (e.g. probably right year,maybe right day/hour)
	if [ -e "/usr/data/time_backup" ] ; then
		date -u -s $(cat /usr/data/time_backup) >/dev/null 2>&1
	fi

	#set cron to periodically backup date
	touch /etc/crontabs/root
	if ! grep -q "time_backup" /etc/crontabs/root; then
		echo '0 0,4,8,12,16,20 * * * date -u  +"%Y.%m.%d-%H:%M:%S" >/usr/data/time_backup' >> /etc/crontabs/root
		/etc/init.d/cron enable
	fi
}

start()
{
	boot
	/etc/init.d/cron restart
}

