#!/bin/sh

menu_name="System Logs"
[ -n `which i18n` ] && {
	menu_name=$(i18n-menu gargoyle.display.system_logread)
}
uci set gargoyle.display.system_logread="$menu_name"
uci set gargoyle.scripts.system_logread='logread.sh'
uci set gargoyle.system.logread='311'
uci commit
