#!/bin/sh /etc/rc.common

START=25

do_lock()
{
	got_lock=0
	local timeout=15
	if [ ! -e /tmp/share_users.lock ] ; then
		touch /tmp/share_users.lock
		got_lock=1
	fi
	echo "$got_lock"
}

do_unlock()
{
	rm -rf /tmp/share_users.lock
}

update_user()
{
	username="$1"
	config_get password "$username" password
	config_get password_salt "$username" password_salt
	config_get password_sha1 "$username" password_sha1
	config_get home_dir      "$username" home_dir	

	if [ -z "home_dir" ] ; then
		home_dir="/tmp/share_home/$username"
	fi
	if [ ! -d "$home_dir" ] ; then
		rm -rf     "$home_dir"
		mkdir -p   "$home_dir"
		chown root "$home_dir"
		chmod 555  "$home_dir"
	fi

	if [ "$username" = "ftp" ] || [ "$username" = "anonymous" ] || [ "$username" = "root" ] || [ "$username" = "daemon" ] || [ "$username" = "network" ] || [ "$username" = "nobody" ] ; then
		echo "ERROR: Username '$username' is not allowed"
		return
	fi
	
	if [ -n "$password" ] ; then
		if [ -z "$password_salt" ] ; then
			random_digit=$(</dev/urandom tr -dc 1-9 | head -c 1)
			length=$(( 20 + $random_digit ))
			password_salt=$(</dev/urandom tr -dc A-Za-z0-9 | head -c $length)
		fi

		new_sha1=$(printf "$password_salt$password" | sha1sum)
		new_sha1=${new_sha1% *}
		if [ "$new_sha1" != "$password_sha1" ] ; then
			
			sed -i "/^$username:*/d" /etc/passwd
			sed -i "/^$username:*/d" /etc/group
			
			local group_num=1000
			local tst=$(grep ":$group_num:" /etc/group)
			while [ -n "$tst" ] ; do
				group_num=$(($group_num+1))
				tst=$(grep ":$group_num:" /etc/group)
			done
			echo "$username:x:$group_num:" >> /etc/group
			
			local user_num="$group_num"
			local tst=$(grep ":.*:$user_num:.*:.*:/.*:/.*$" /etc/passwd)
			while [ -n "$tst" ] ; do
				user_num=$((user_num+1))
				tst=$(grep ":.*:$user_num:.*:.*:/.*:/.*$" /etc/passwd)
			done
			echo "$username:x:$user_num:$group_num:$username:$home_dir:/bin/false" >> /etc/passwd

			uci_set    "share_users" "$username" password_salt "$password_salt"
			uci_set    "share_users" "$username" password_sha1 "$new_sha1"
		fi
		uci_remove "share_users" "$username" password
		uci_commit
	fi
	cur_home_dir=$(grep "^$username:" /etc/passwd)
	cur_home_dir=${cur_home_dir%:/bin/false*}
	cur_home_dir=${cur_home_dir#*:*:*:*:*:}
	if [ "$cur_home_dir" != "$home_dir" ] ; then
		local home_line=$(grep "^$username:" /etc/passwd)
		home_line=${home_line%:*:/bin/false}
		home_line="$home_line:$home_dir:/bin/false"
		sed -i "/^$username:*/d" /etc/passwd
		echo "$home_line" >> /etc/passwd
	fi

}

start()
{
	got_lock=$(do_lock)
	if [ "$got_lock" = "1" ] ; then
		config_load "share_users"
		config_foreach update_user "user"
		do_unlock
	fi
}

